name: do_you_parental_control
description: "DO you - Advanced Parental Control & Family Shield Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.0
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#1A73E8"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"